--[[
	Author: Fernando

	Discord Webhooks MTA Resource (System)

	/!\ Unless you know what you are doing, do not edit this file /!\
]]

-- Custom Events:
addEvent("discord_webhooks:send", true) -- source must always be root
addEvent("discord_webhooks:sendToURL", true) -- source must always be root

local function internalSendRequest(name, url, content, callBackEvent)
	local postData
	if type(content) == "string" then
		postData = {
			content = content
		}
	elseif type(content) == "table" then
		local valid, additional = validateEmbed(content)
		if not valid then
			return false, "internalSendRequest ERROR: Invalid embed: "..tostring(additional).." (argument 2)"
		end
		postData = {
			["embeds"] = {additional}
		}
	end
	postData = toJSON(postData, true)
	-- make it only JSON object and not [JSON object] (it's inside an array for no reason)
	if string.sub(postData, 1, 1) == "[" then
		postData = string.sub(postData, 2, -2)
	end
	if (LOG_INFO_DEBUG) then
		outputDebugString("Sending to URL '"..url.."' with data:", 3)
		outputDebugString(postData, 3)
	end
	local function callBackFunction(responseData, responseInfo)
		triggerEvent(callBackEvent.name, callBackEvent.source, {
			name = name, -- false if sendToURL is used
			url = url,
			content = postData,
			responseData = responseData,
			responseInfo = responseInfo
		}, unpack(callBackEvent.args or {}))
	end
	if callBackEvent == nil then
		callBackFunction = function() end
	end
	local request = fetchRemote(url, {
		queueName = md5(url),
		connectionAttempts = 3,
		connectTimeout = 5000,
		method = "POST",
		postIsBinary = false,
		headers = {
			["Content-Type"] = "application/json"
		},
		postData = postData,
	}, callBackFunction)
	if not request then
		return false, "internalSendRequest ERROR: fetchRemote failed"
	end
	return request
end

local function internalSend(name, content, callBackEvent)
	if type(name) ~= "string" then
		return false, "Bad argument @ 'send' [Expected string at argument 1, got "..type(name).."]"
	end
	local url = WEB_HOOKS[name]
	if type(url) ~= "string" then
		return false, "Bad argument @ 'send' [Webhook name '"..name.."' (argument 1) does not have a valid URL]"
	end
	if not (type(content)=="string" or (type(content)=="table")) then
		return false, "Bad argument @ 'send' [Expected string or table at argument 2, got "..type(content).."]"
	end
	if callBackEvent ~= nil then
		if (type(callBackEvent) ~= "table") then
			return false, "Bad argument @ 'send' [Expected table at argument 3, got "..type(callBackEvent).."]"
		end
		if (type(callBackEvent.name) ~= "string") then
			return false, "Bad argument @ 'send' [Expected string at argument 3.name, got "..type(callBackEvent.name).."]"
		end
		if (not isElement(callBackEvent.source) and callBackEvent.source ~= root) then
			return false, "Bad argument @ 'send' [Expected element at argument 3.source, got "..type(callBackEvent.source).."]"
		end
		if (callBackEvent.args ~= nil) and (type(callBackEvent.args) ~= "table") then
			return false, "Bad argument @ 'send' [Expected table at argument 3.args, got "..type(callBackEvent.args).."]"
		end
	end
	return internalSendRequest(name, url, content, callBackEvent)
end

-- Exported function
function send(...)
	local result, reason = internalSend(...)
	if (not result) and (LOG_ERRORS_DEBUG == true) then
		outputDebugString(tostring(reason), 1)
	end
	return result, reason
end
addEventHandler("discord_webhooks:send", root, send, false)

local function isValidURL(url)
	return url:match("[a-z]+://[^ >,;]+")
end

local function internalSendToURL(url, content, callBackEvent)
	
	if type(url) ~= "string" then
		return false, "Bad argument @ 'sendToURL' [Expected string at argument 1, got "..type(url).."]"
	end
	if not isValidURL(url) then
		outputDebugString("sendToURL: URL may not be valid: "..url, 2)
	end
	if type(content) ~= "string" and type (content) ~= "table" then
		return false, "Bad argument @ 'sendToURL' [Expected string or table at argument 2, got "..type(content).."]"
	end
	if callBackEvent ~= nil then
		if type(callBackEvent) ~= "table" then
			return false, "Bad argument @ 'sendToURL' [Expected table at argument 3, got "..type(callBackEvent).."]"
		end
		if type(callBackEvent.name) ~= "string" then
			return false, "Bad argument @ 'sendToURL' [Expected string at argument 3.name, got "..type(callBackEvent.name).."]"
		end
		if not (isElement(callBackEvent.source) or callBackEvent.source == root) then
			return false, "Bad argument @ 'sendToURL' [Expected element at argument 3.source, got "..type(callBackEvent.source).."]"
		end
		if callBackEvent.args ~= nil and type(callBackEvent.args) ~= "table" then
			return false, "Bad argument @ 'send' [Expected table at argument 3.args, got "..type(callBackEvent.args).."]"
		end
	end
	local foundName = false
	for name, webhookURL in pairs(WEB_HOOKS) do
		if webhookURL == url then
			foundName = name
			break
		end
	end
	return internalSendRequest(foundName, url, content, callBackEvent)
end

-- Exported function
function sendToURL(...)
	local result, reason = internalSendToURL(...)
	if (not result) and (LOG_ERRORS_DEBUG == true) then
		outputDebugString(tostring(reason), 1)
	end
	return result, reason
end
addEventHandler("discord_webhooks:sendToURL", root, sendToURL, false)

addEventHandler("onResourceStart", resourceRoot, function()
	if type(WEB_HOOKS) ~= "table" then
		outputServerLog("WEB_HOOKS is not a table. Please check your config.lua file.")
		return cancelEvent()
	end
	for name, url in pairs(WEB_HOOKS) do
		if type(name) ~= "string" then
			outputServerLog("WEB_HOOKS contains a non-string key. Please check your config.lua file.")
			return cancelEvent()
		end
		if type(url) ~= "string" then
			outputServerLog("WEB_HOOKS contains a non-string value. Please check your config.lua file.")
			return cancelEvent()
		end
	end
	-- No critical errors, continue
	if type(SETTING_DISABLE) == "string"  then
		local settingValue = tostring(get(SETTING_DISABLE))
		if (settingValue == "true" or settingValue == "1") then
			if (LOG_INFO_DEBUG) then
				outputDebugString("Webhooks are disabled by the server's settings registry.", 3)
			end
			send = function() return true end
			sendToURL = function() return true end
			return
		end
	end
	if (LOG_INFO_DEBUG) then
		outputDebugString("Initialization complete ("..#WEB_HOOKS.." webhooks declared).", 3)
	end
end, false)
